"use client"
import { Inter, Bebas_Neue, Russo_One, Cinzel } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// wagmi + WalletConnect imports
import { WagmiProvider, createConfig } from "wagmi";
import { mainnet, polygon, sepolia } from "wagmi/chains";
import { http } from "viem";
import { walletConnect, injected } from "wagmi/connectors";
import { createWeb3Modal } from "@web3modal/wagmi/react";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import GlobalProviders from "@/context/GlobalProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight:'400'
});
const ruso = Russo_One({
  variable: "--font-ruso",
  subsets: ["latin"],
  weight:'400'
});

const metadata = {
  title: "Liberty Poker",
  description: "Generated by create next app",
  // name: "Poker-Game",
  description: "Decentralized Poker Game",
  url: "https://yourdomain.com", // replace with your domain
  icons: ["https://yourdomain.com/icon.png"], // replace with your icon URL
};
// 1. Get WalletConnect projectId from .env
const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID;

// 3. Create wagmi config with connectors
const config = createConfig({
  chains: [sepolia, polygon, mainnet],
  connectors: [
    injected({ 
      shimDisconnect: true,
      target: 'metaMask'
    }), // MetaMask browser extension
    injected({ 
      shimDisconnect: true,
      target: 'coinbaseWallet'
    }), // Coinbase Wallet browser extension
    walletConnect({ projectId,metadata, showQrModal: true }), // WalletConnect QR + deep link
  ],
  transports: {
    [sepolia.id]: http(),
    [polygon.id]: http(),
    [mainnet.id]: http(),
  },
  multiInjectedProviderDiscovery: true,
});

// 4. Create Web3Modal outside the component
createWeb3Modal({
  wagmiConfig: config,
  projectId,
  themeMode: "dark",
  metadata
});

// 5. Create a query client
const queryClient = new QueryClient();



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${bebas.variable} ${ruso.variable} ${cinzel.variable} antialiased`}
      >
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
            <GlobalProviders>
              {children}
            </GlobalProviders>
          </QueryClientProvider>
        </WagmiProvider>
        
        <Toaster
          richColors={true}
          expand={false}
          visibleToasts={3}
          position="top-center"
        />
      </body>
    </html>
  );
}
